/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/recipe` | `/recipe`; params?: Router.UnknownInputParams; } | { pathname: `/auth/authIndex`; params?: Router.UnknownInputParams; } | { pathname: `/auth/protected`; params?: Router.UnknownInputParams; } | { pathname: `/future/search`; params?: Router.UnknownInputParams; } | { pathname: `/future/upload`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/recipe` | `/recipe`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/authIndex`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/protected`; params?: Router.UnknownOutputParams; } | { pathname: `/future/search`; params?: Router.UnknownOutputParams; } | { pathname: `/future/upload`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/recipe${`?${string}` | `#${string}` | ''}` | `/recipe${`?${string}` | `#${string}` | ''}` | `/auth/authIndex${`?${string}` | `#${string}` | ''}` | `/auth/protected${`?${string}` | `#${string}` | ''}` | `/future/search${`?${string}` | `#${string}` | ''}` | `/future/upload${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/recipe` | `/recipe`; params?: Router.UnknownInputParams; } | { pathname: `/auth/authIndex`; params?: Router.UnknownInputParams; } | { pathname: `/auth/protected`; params?: Router.UnknownInputParams; } | { pathname: `/future/search`; params?: Router.UnknownInputParams; } | { pathname: `/future/upload`; params?: Router.UnknownInputParams; };
    }
  }
}
